### ISSUE TITLE
Quick buy port 6003

### ISSUE THREAD

**Issue by pooleja** [21dotco/ping21#7]
Should the quick buy url in the manifest be port 6002 (currently says :6003)?  This threw me off when I was playing with it.

**Comment by wbnns** [comment]
@pooleja Hi there! In [ping21-server.py](https://github.com/21dotco/ping21/blob/master/ping21-server.py) and [manifest.yaml](https://github.com/21dotco/ping21/blob/master/manifest.yaml) it is 6002.

What file are you referencing that is showing 6003?

**Comment by pooleja** [comment]
Sorry... should have been more specific.  It is in the quick buy url:
x-21-quick-buy: "$ 21 buy url http://<ZEROTIER IP>:6003/?uri=google.com"

**Comment by wbnns** [comment]
@pooleja Got it! Thanks for clarifying and also for bringing this to our attention. Apologies for not catching that the first time when you brought it up. This is now resolved. 👍
